
package br.com.prmarinho.service.store.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebStoreServiceSoapService", targetNamespace = "http://webservice.store.web.com.br/", wsdlLocation = "http://localhost:8080/app-service-store-ws-cxf/service/WebStoreServiceSoap?wsdl")
public class WebStoreServiceSoapService
    extends Service
{

    private final static URL WEBSTORESERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSTORESERVICESOAPSERVICE_EXCEPTION;
    private final static QName WEBSTORESERVICESOAPSERVICE_QNAME = new QName("http://webservice.store.web.com.br/", "WebStoreServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/app-service-store-ws-cxf/service/WebStoreServiceSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSTORESERVICESOAPSERVICE_WSDL_LOCATION = url;
        WEBSTORESERVICESOAPSERVICE_EXCEPTION = e;
    }

    public WebStoreServiceSoapService() {
        super(__getWsdlLocation(), WEBSTORESERVICESOAPSERVICE_QNAME);
    }

    public WebStoreServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSTORESERVICESOAPSERVICE_QNAME, features);
    }

    public WebStoreServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, WEBSTORESERVICESOAPSERVICE_QNAME);
    }

    public WebStoreServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSTORESERVICESOAPSERVICE_QNAME, features);
    }

    public WebStoreServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebStoreServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebStoreServiceSoap
     */
    @WebEndpoint(name = "WebStoreServiceSoapPort")
    public WebStoreServiceSoap getWebStoreServiceSoapPort() {
        return super.getPort(new QName("http://webservice.store.web.com.br/", "WebStoreServiceSoapPort"), WebStoreServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebStoreServiceSoap
     */
    @WebEndpoint(name = "WebStoreServiceSoapPort")
    public WebStoreServiceSoap getWebStoreServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.store.web.com.br/", "WebStoreServiceSoapPort"), WebStoreServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSTORESERVICESOAPSERVICE_EXCEPTION!= null) {
            throw WEBSTORESERVICESOAPSERVICE_EXCEPTION;
        }
        return WEBSTORESERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
