
package br.com.prmarinho.service.store.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebStoreServiceSoap", targetNamespace = "http://webservice.store.web.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebStoreServiceSoap {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "desabilitarProduto", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.DesabilitarProduto")
    @ResponseWrapper(localName = "desabilitarProdutoResponse", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.DesabilitarProdutoResponse")
    public void desabilitarProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.prmarinho.service.store.client.OutGameDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarJogos", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.ListarJogos")
    @ResponseWrapper(localName = "listarJogosResponse", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.ListarJogosResponse")
    public List<OutGameDTO> listarJogos();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.prmarinho.service.store.client.OutGameDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarJogo", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.BuscarJogo")
    @ResponseWrapper(localName = "buscarJogoResponse", targetNamespace = "http://webservice.store.web.com.br/", className = "br.com.prmarinho.service.store.client.BuscarJogoResponse")
    public OutGameDTO buscarJogo(
        @WebParam(name = "arg0", targetNamespace = "")
        InGameDTO arg0);

}
